services:
  - type: web
    name: pe-prn232-backend
    plan: free
    runtime: docker
    dockerfilePath: Backend/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: IMAGES_DIR
        value: /opt/render/images
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_PUBLIC_BASE_URL
        sync: false

  - type: web
    runtime: static
    name: pe-prn232-frontend
    rootDir: Frontend
    plan: free
    buildCommand: npm install && VITE_API_BASE_URL="https://${BACKEND_HOST}.onrender.com" npm run build
    staticPublishPath: dist
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: pe-prn232-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html