services:
  - type: web
    name: pe-prn232-backend
    rootDir: Backend
    plan: free
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: dotnet ./out/Backend.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: IMAGES_DIR
        value: /opt/render/images

  - type: web
    runtime: static
    name: pe-prn232-frontend
    rootDir: Frontend
    plan: free
    buildCommand: npm install && VITE_API_BASE_URL="https://${BACKEND_HOST}.onrender.com" npm run build
    staticPublishPath: dist
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: pe-prn232-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html